modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tetra"
    mandatory=true
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mutil"
    mandatory=true
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
  modId = "soul_fire_d"
  mandatory = true # Change this to false if Soul Fire'd is not required.
  versionRange = "[4.0.2,)"
  ordering = "AFTER"
  side = "BOTH"